apiVersion: v1
kind: Service
metadata:
  name: films-api-svc
  namespace: star-wars-api-ns
spec:
  type: ClusterIP
  selector:
    app: films-api
  ports:
    - protocol: TCP
      targetPort: 8081
      port: 8081
