apiVersion: v1
kind: Service
metadata:
  name: gateway-api-svc
  namespace: star-wars-api-ns
spec:
  type: NodePort
  selector:
    app: gateway-api
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
      nodePort: 30081
